services:
  - type: web
    name: school-crm-backend
    runtime: node
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: school-crm-db
          property: connectionString
