services:
  - type: web
    name: school-crm-backend
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: school-crm-db
          property: connectionString
